from doks import doks
from unittest import TestCase, mock
import os

SAMPLE_FILE = os.path.join(os.path.dirname(__file__), 'sample.py')
TIMESTAMP = '2020-05-28T16:26:07.629835'


class TestDoks(TestCase):
    maxDiff = 100000

    @mock.patch('doks.doks._timestamp', return_value=TIMESTAMP)
    def test_full(self, _timestamp):
        actual = list(doks._doks(SAMPLE_FILE))
        print(*actual, sep='\n')
        assert actual == EXPECTED


EXPECTED = """\
Top level docs

API
***

``test.sample.function(a, b, c='hello', **kwargs)``
---------------------------------------------------

(`test/sample.py, 4-6 <https://github.com/rec/doks/blob/master/test/\
sample.py#L4-L6>`_)

This is a function().

Class `test.sample.Class``
==========================

(`test/sample.py, 8-37 <https://github.com/rec/doks/blob/master/test/\
sample.py#L8-L37>`_)

This is a class

``test.sample.Class.__init__(self, *args, **kwargs)``
-----------------------------------------------------

(`test/sample.py, 11-15 <https://github.com/rec/doks/blob/master/test/\
sample.py#L11-L15>`_)

a constructor

``test.sample.Class.public(self, foo, bar, baz)``
-------------------------------------------------

(`test/sample.py, 17-31 <https://github.com/rec/doks/blob/master/test/\
sample.py#L17-L31>`_)

A public method.

ARGUMENTS
  foo
    a foo

  bar
    a bar

  baz
    no idea

``test.sample.Class.undocumented(self, foo, bar, baz)``
-------------------------------------------------------

(`test/sample.py, 32-34 <https://github.com/rec/doks/blob/master/test/\
sample.py#L32-L34>`_)


(automatically generated by `doks <https://github.com/rec/doks/>`_ on \
2020-05-28T16:26:07.629835)
""".splitlines()
