|b1| |b2| |b3| |b4| |b5| |b6| |b7| |b8| |b9| |b10|

.. |b1| image:: https://img.shields.io/travis/rec/safer
   :alt: Travis (.org)

.. |b2| image:: https://img.shields.io/codecov/c/github/rec/safer
   :alt: Codecov

.. |b3| image:: https://img.shields.io/github/v/release/rec/safer
   :alt: GitHub release (latest SemVer)

.. |b4| image:: https://img.shields.io/pypi/pyversions/safer
   :alt: PyPI - Python Version

.. |b5| image:: https://img.shields.io/github/last-commit/rec/safer
   :alt: GitHub last commit

.. |b6| image:: https://img.shields.io/github/languages/top/rec/safer
   :alt: GitHub top language

.. |b7| image:: https://img.shields.io/codefactor/grade/github/rec/safer
   :alt: CodeFactor Grade

.. |b8| image:: https://img.shields.io/pypi/l/safer
   :alt: PyPI - License

.. |b9| image:: https://img.shields.io/codefactor/grade/github/rec/safer
   :alt: CodeFactor Grade

.. |b10| image:: https://img.shields.io/github/languages/code-size/rec/safer
   :alt: GitHub code size in bytes
